src/objects/Github_Integration_Users__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>    
    <description>Users who are authorized to use the integration between Github and Agile Accelerator</description>
    <fields>
        <fullName>Github_Username__c</fullName>
        <externalId>true</externalId>
        <label>Github Username</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Github Integration Users</label>
</CustomObject>

src/objects/GitHub_Link__c.object
<CustomObject>
    <fields>
        <fullName>GitHub_Unique_Id__c</fullName>
        <inlineHelpText>The composite Id of the record defined in GithubToAgileAccelerator.getUniqueId() - originally &lt;repository_name&gt;_&lt;github_record_type&gt;_&lt;github_record_id&gt;</inlineHelpText>
        <label>GitHub Unique Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Work record in Agile Accelerator.</inlineHelpText>
        <label>Work</label>
        <referenceTo>agf__ADM_Work__c</referenceTo>
        <relationshipLabel>GitHub Links</relationshipLabel>
        <relationshipName>GitHub_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GitHub Link</label>
    <nameField>
        <displayFormat>Git-{0000000}</displayFormat>
        <label>GitHub Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GitHub Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Github_Repositories__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping of Github repositories to product tags in Agile Accelerator</description>
    <fields>
        <fullName>Github_Repository_Id__c</fullName>
        <description>repository.id</description>
        <label>Github Repository Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
      <fullName>Token__c</fullName>
      <description>Auth token for this repository</description>
      <inlineHelpText>Authorization token used for Lurch to post back to comment or issues when synced with Agile Accelerator.</inlineHelpText>
      <label>Authorization Token</label>
      <length>255</length>
      <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <description>The Id of the corresponding Product Tag in Agile Accelerator.</description>
        <inlineHelpText>The Id of the corresponding Product Tag in Agile Accelerator.</inlineHelpText>
        <label>Product Tag</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Github Repositories</label>
</CustomObject>

src/objects/Github_Request__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>attach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>remove</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Github_Record_Id__c</fullName>
        <label>Github Record Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Github_Record_Type__c</fullName>
        <label>Github Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pull Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Github_Record_URL__c</fullName>
        <label>Github Record URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Github_Repository__c</fullName>
        <inlineHelpText>The name of the repository in Github.</inlineHelpText>
        <label>Github Repository</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Github_Unique_Id__c</fullName>
        <description>Github Record Type + &apos; &apos; + Github Record Id =&gt; Issue 9</description>
        <label>Github_Unique_Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Github_Username__c</fullName>
        <label>Github Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <inlineHelpText>The target of the event, i.e. the name of the record to attach in **lurch:attach W-12345.</inlineHelpText>
        <label>Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Github Request</label>
    <nameField>
        <displayFormat>GitReq-{00000000}</displayFormat>
        <label>Github Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Github Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GithubRequestHandler_TEST.cls
@isTest
private class GithubRequestHandler_TEST {

  @TestSetup
  static void setupTestData() {
     agf__ADM_Scrum_Team__c team = AATestData.scrumTeam;
     agf__ADM_Product_Tag__c tag = AATestData.productTag;

    Github_Integration_Users__c giu = new Github_Integration_Users__c(
      Name = 'User1',
      Github_Username__c = 'theusername'
    );
    insert giu;

    Github_Repositories__c gr = new Github_Repositories__c(
      Name = 'sfdo-github',
      Github_Repository_Id__c = 'sfdo-github',
      Token__c = '1234567890',
      Product_Tag__c = tag.id
    );
    insert gr;
  }

  //add, attach, remove, comment
  @isTest
  static void testAddProcess() {

    Github_Request__c gr_add = new Github_Request__c(
      Body__c = 'The body of my issue comment **lurch: add',
      Title__c = 'The title of my issue',
      Github_Username__c = 'theusername',
      Github_Record_Id__c = '137538186',
      Github_Record_URL__c = 'https://github.com/SalesforceFoundation/sfdo-github/issues/16#issuecomment-137538186',
      Github_Repository__c = 'sfdo-github',
      Github_Record_Number__c = '16',
      Action__c = 'add',
      Status__c = 'New'
    );
    insert gr_add;

    Github_Request__c gr_add2 = new Github_Request__c(
      Body__c = 'The body of my issue comment2 **lurch: add',
      Title__c = 'The title of my issue2',
      Github_Username__c = 'theusername',
      Github_Record_Id__c = '1375332326',
      Github_Record_URL__c = 'https://github.com/SalesforceFoundation/sfdo-github/issues/17#issuecomment-137538186',
      Github_Repository__c = 'sfdo-github',
      Github_Record_Number__c = '17',
      Action__c = 'add',
      Status__c = 'New'
    );
    insert gr_add2;

    Test.startTest();
    GithubRequestHandler grh = new GithubRequestHandler();
    grh.processRequests();
    Test.stopTest();

    Github_Request__c gr = [ SELECT Id, Body__c, Title__c, Comment__c, Action__c, Target__c,
        Github_Record_Id__c, Github_Record_Type__c, Github_Record_URL__c,
        Github_Repository__c, Github_Username__c, Status__c, Github_Unique_Id__c,
        Github_Record_Number__c
        FROM Github_Request__c
        WHERE Github_Record_URL__c = 'https://github.com/SalesforceFoundation/sfdo-github/issues/16#issuecomment-137538186'
        AND
        Action__c = 'add'
        ORDER BY CreatedDate
    ];

    System.assertEquals('Processed', gr.Status__c);
    System.assertNotEquals(gr.Target__c, null);
    Github_Link__c gl = [SELECT Id, Work__c, Github_Unique_Id__c from Github_Link__c where Github_Unique_Id__c = 'sfdo-github_16' limit 1];
    System.assertEquals(gl.Github_Unique_Id__c, gr.Github_Unique_Id__c);
    System.assertNotEquals(gl.Work__c, null);
  }

  @isTest
  static void testRemoveProcess() {

    Github_Request__c gr_remove = new Github_Request__c(
      Body__c = 'The body of my issue comment **lurch: remove',
      Title__c = 'The title of my issue',
      Github_Username__c = 'theusername',
      Github_Record_Id__c = '137538186',
      Github_Record_URL__c = 'https://github.com/SalesforceFoundation/sfdo-github/issues/16#issuecomment-137538186',
      Github_Repository__c = 'sfdo-github',
      Github_Record_Number__c = '16',
      Action__c = 'remove',
      Status__c = 'New'
    );
    insert gr_remove;

    agf__ADM_Work__c work = AATestData.work;

    Github_Link__c gl = new Github_Link__c(
      Work__c = work.id,
      Github_Unique_Id__c = 'sfdo-github_16'
    );
    insert gl;

    Test.startTest();
    GithubRequestHandler grh = new GithubRequestHandler();
    grh.processRequests();
    Test.stopTest();

    System.assertEquals(0, [SELECT count() FROM Github_Link__c WHERE Work__c = :work.id]);
    System.assertEquals('Processed', [SELECT Status__c from Github_Request__c where Id = :gr_remove.id].Status__c);
  }

  @isTest
  static void testAttachProcess() {

    agf__ADM_Work__c work = AATestData.work;
    String wname = [SELECT Name from agf__ADM_Work__c where id = :work.id].Name;

    Github_Request__c gr_attach = new Github_Request__c(
      Body__c = 'The body of my issue comment **lurch: attach ' + wname,
      Title__c = 'The title of my issue',
      Github_Username__c = 'theusername',
      Github_Record_Id__c = '137538186',
      Github_Record_URL__c = 'https://github.com/SalesforceFoundation/sfdo-github/issues/16#issuecomment-137538186',
      Github_Repository__c = 'sfdo-github',
      Github_Record_Number__c = '16',
      Action__c = 'attach',
      Status__c = 'New',
      Target__c = wname
    );
    insert gr_attach;

    Test.startTest();
    GithubRequestHandler grh = new GithubRequestHandler();
    grh.processRequests();
    Test.stopTest();

    System.assertEquals(1, [SELECT count() FROM Github_Link__c WHERE Work__c = :work.id]);
    System.assertEquals('Processed', [SELECT Status__c from Github_Request__c where Id = :gr_attach.id].Status__c);
  }

  @isTest
  static void testCommentProcess() {
    agf__ADM_Work__c work = AATestData.work;

    Github_Request__c gr_comment = new Github_Request__c(
      Body__c = 'The body of my issue comment',
      Title__c = 'The title of my issue',
      Github_Username__c = 'theusername',
      Github_Record_Id__c = '137538186',
      Github_Record_URL__c = 'https://github.com/SalesforceFoundation/sfdo-github/issues/16#issuecomment-137538186',
      Github_Repository__c = 'sfdo-github',
      Github_Record_Number__c = '16',
      Action__c = 'comment',
      Status__c = 'New',
      Target__c = work.id
    );
    insert gr_comment;

    Github_Link__c gl = new Github_Link__c(
      Work__c = work.id,
      Github_Unique_Id__c = 'sfdo-github_16'
    );
    insert gl;

    Test.startTest();
    GithubRequestHandler grh = new GithubRequestHandler();
    grh.processRequests();
    Test.stopTest();

    FeedItem fi = [SELECT id, Body from FeedItem where ParentId = :work.id ORDER BY CreatedDate desc LIMIT 1];

    System.assertEquals('@theusername: ' + gr_comment.Body__c, fi.Body);
  }

  @isTest
  static void testExecuteMethod() {
    String CRON_EXP = '0 0 0 15 3 ? 2022';
    Test.startTest();
    String jobId = System.schedule('ScheduleApexClassTest', CRON_EXP, new GithubRequestHandler());
    Test.stopTest();
  }
}