src/objects/Github_Integration_Users__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>    
    <description>Users who are authorized to use the integration between Github and Agile Accelerator</description>
    <fields>
        <fullName>Github_Username__c</fullName>
        <externalId>true</externalId>
        <label>Github Username</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Github Integration Users</label>
</CustomObject>

src/objects/GitHub_Link__c.object
<CustomObject>
    <fields>
        <fullName>GitHub_Unique_Id__c</fullName>
        <inlineHelpText>The composite Id of the record defined in GithubToAgileAccelerator.getUniqueId() - originally &lt;repository_name&gt;_&lt;github_record_type&gt;_&lt;github_record_id&gt;</inlineHelpText>
        <label>GitHub Unique Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The Work record in Agile Accelerator.</inlineHelpText>
        <label>Work</label>
        <referenceTo>agf__ADM_Work__c</referenceTo>
        <relationshipLabel>GitHub Links</relationshipLabel>
        <relationshipName>GitHub_Links</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GitHub Link</label>
    <nameField>
        <displayFormat>Git-{0000000}</displayFormat>
        <label>GitHub Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GitHub Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Github_Repositories__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping of Github repositories to product tags in Agile Accelerator</description>
    <fields>
        <fullName>Github_Repository_Id__c</fullName>
        <description>repository.id</description>
        <label>Github Repository Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
      <fullName>Token__c</fullName>
      <description>Auth token for this repository</description>
      <inlineHelpText>Authorization token used for Lurch to post back to comment or issues when synced with Agile Accelerator.</inlineHelpText>
      <label>Authorization Token</label>
      <length>255</length>
      <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Tag__c</fullName>
        <description>The Id of the corresponding Product Tag in Agile Accelerator.</description>
        <inlineHelpText>The Id of the corresponding Product Tag in Agile Accelerator.</inlineHelpText>
        <label>Product Tag</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Github Repositories</label>
</CustomObject>

src/objects/Github_Request__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>attach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>remove</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Github_Unique_Id__c</fullName>
        <description>Github Record Type + &apos; &apos; + Github Record Id =&gt; Issue 9</description>
        <label>Github_Unique_Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Github_Username__c</fullName>
        <label>Github Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Github Request</label>
    <nameField>
        <displayFormat>GitReq-{00000000}</displayFormat>
        <label>Github Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Github Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GithubWebhookHandler_Test.cls
@isTest
private class GithubWebhookHandler_Test {

  @TestSetup
  static void setupTestData() {
     agf__ADM_Scrum_Team__c team = AATestData.scrumTeam;
     agf__ADM_Product_Tag__c tag = AATestData.productTag;

    Github_Integration_Users__c giu = new Github_Integration_Users__c(
      Name = 'User1',
      Github_Username__c = 'baxterthehacker'
    );
    insert giu;

    Github_Repositories__c gr = new Github_Repositories__c(
      Name = 'public-repo',
      Github_Repository_Id__c = '35129377',
      Token__c = '1234567890',
      Product_Tag__c = AATestData.productTag.Id
    );
    insert gr;
  }

  @isTest
  static void testIssuePost(){
    RestRequest req = new RestRequest(); // Build the REST Request for testing
    req.addHeader('X-GitHub-Event', 'issues');
    req.addHeader('Content-Type', 'application/json'); // Add a JSON Header as it is validated
    req.requestURI = GithubToAgileAccelerator.INSTANCE_URL + '/services/apexrest/github/webhook';
    req.httpMethod = 'POST';
    req.requestBody = Blob.valueof(GithubWebhookHandler_Mock.mockIssuesEvent('**lurch: add')); // Add JSON Message as a POST
    RestResponse res = new RestResponse();
    RestContext.request = req;
    RestContext.response = res;
    Test.startTest();
    GithubWebhookHandler.receiveEvent();
    Test.stopTest();
    system.assertEquals(1, [SELECT count() FROM Github_Request__c where Status__c = 'New']);
  }

  @isTest
  static void testIssueCommentPost(){
    RestRequest req = new RestRequest(); // Build the REST Request for testing
    req.addHeader('X-GitHub-Event', 'issue_comment');
    req.addHeader('Content-Type', 'application/json'); // Add a JSON Header as it is validated
    req.requestURI = GithubToAgileAccelerator.INSTANCE_URL + '/services/apexrest/github/webhook';
    req.httpMethod = 'POST';
    req.requestBody = Blob.valueof(GithubWebhookHandler_Mock.mockIssueCommentEvent('**lurch: add')); // Add JSON Message as a POST
    RestResponse res = new RestResponse();
    RestContext.request = req;
    RestContext.response = res;
    Test.startTest();
    GithubWebhookHandler.receiveEvent();
    Test.stopTest();
    system.assertEquals(1, [SELECT count() FROM Github_Request__c where Status__c = 'New']);
  }

  @isTest
  static void testPullRequestPost(){
    RestRequest req = new RestRequest(); // Build the REST Request for testing
    req.addHeader('X-GitHub-Event', 'pull_request');
    req.addHeader('Content-Type', 'application/json'); // Add a JSON Header as it is validated
    req.requestURI = GithubToAgileAccelerator.INSTANCE_URL + '/services/apexrest/github/webhook';
    req.httpMethod = 'POST';
    req.requestBody = Blob.valueof(GithubWebhookHandler_Mock.mockPullRequestEvent('**lurch: add')); // Add JSON Message as a POST
    RestResponse res = new RestResponse();
    RestContext.request = req;
    RestContext.response = res;
    Test.startTest();
    GithubWebhookHandler.receiveEvent();
    Test.stopTest();
    system.assertEquals(1, [SELECT count() FROM Github_Request__c where Status__c = 'New']);
  }

  @isTest
  static void testCommentOnExistingIssue(){
    agf__ADM_Work__c work = AATestData.work;

    Github_Link__c gl = new Github_Link__c(
      Work__c = work.id,
      Github_Unique_Id__c = 'public-repo_2'
    );
    insert gl;

    RestRequest req = new RestRequest(); // Build the REST Request for testing
    req.addHeader('X-GitHub-Event', 'issue_comment');
    req.addHeader('Content-Type', 'application/json'); // Add a JSON Header as it is validated
    req.requestURI = GithubToAgileAccelerator.INSTANCE_URL + '/services/apexrest/github/webhook';
    req.httpMethod = 'POST';
    req.requestBody = Blob.valueof(GithubWebhookHandler_Mock.mockIssueCommentEvent('a random comment')); // Add JSON Message as a POST
    RestResponse res = new RestResponse();
    RestContext.request = req;
    RestContext.response = res;
    Test.startTest();
    GithubWebhookHandler.receiveEvent();
    Test.stopTest();
    system.assertEquals(1, [SELECT count() FROM Github_Request__c where Status__c = 'New' AND Action__c = 'comment']);
  }

  @isTest
  static void testInvalidLurchCommand(){
    RestRequest req = new RestRequest(); // Build the REST Request for testing
    req.addHeader('X-GitHub-Event', 'issue_comment');
    req.addHeader('Content-Type', 'application/json'); // Add a JSON Header as it is validated
    req.requestURI = GithubToAgileAccelerator.INSTANCE_URL + '/services/apexrest/github/webhook';
    req.httpMethod = 'POST';
    req.requestBody = Blob.valueof(GithubWebhookHandler_Mock.mockIssueCommentEvent('**lurch: garbage')); // Add JSON Message as a POST
    RestResponse res = new RestResponse();
    RestContext.request = req;
    RestContext.response = res;
    Test.startTest();
    GithubWebhookHandler.receiveEvent();
    Test.stopTest();
    system.assertEquals(0, [SELECT count() FROM Github_Request__c where Status__c = 'New']);
  }
}