src/objects/Github_Request__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <label>Action</label>
        <picklist>
            <picklistValues>
                <fullName>add</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>attach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>remove</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Github_Record_Id__c</fullName>
        <label>Github Record Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Github_Record_Type__c</fullName>
        <label>Github Record Type</label>
        <picklist>
            <picklistValues>
                <fullName>Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pull Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Github_Record_URL__c</fullName>
        <label>Github Record URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Github_Repository__c</fullName>
        <inlineHelpText>The name of the repository in Github.</inlineHelpText>
        <label>Github Repository</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Github_Unique_Id__c</fullName>
        <description>Github Record Type + &apos; &apos; + Github Record Id =&gt; Issue 9</description>
        <label>Github_Unique_Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Github_Username__c</fullName>
        <label>Github Username</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Processed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <inlineHelpText>The target of the event, i.e. the name of the record to attach in **lurch:attach W-12345.</inlineHelpText>
        <label>Target</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Github Request</label>
    <nameField>
        <displayFormat>GitReq-{00000000}</displayFormat>
        <label>Github Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Github Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GithubRequestHandler.cls
global without sharing class GithubRequestHandler implements Schedulable {

    global void execute(SchedulableContext sc) {
        processRequests();
    }

    global void processRequests() {
        // action => list of requests
        // i.e. add => list of requests to add
        Map<String, List<Github_Request__c>> requestsByAction = new Map<String, List<Github_Request__c>>();
        
        // github record id => last action listed on that Id
        Map<String, String> lastAction = new Map<String, String>();

        for (Github_Request__c githubRequest : 
            [ SELECT Id, Body__c, Title__c, Comment__c, Action__c, Target__c, 
                Github_Record_Id__c, Github_Record_Type__c, Github_Record_URL__c,
                Github_Repository__c, Github_Username__c, Status__c 
                FROM Github_Request__c 
                WHERE Status__c = 'New' 
                ORDER BY CreatedDate  
            ]) {
            // add to action map
            if (requestsByAction.get(githubRequest.Action__c) == null) {
                requestsByAction.put(githubRequest.Action__c, new List<Github_Request__c>{ githubRequest });    
            } else {
                requestsByAction.get(githubRequest.Action__c).add(githubRequest);
            }
            lastAction.put(githubRequest.Github_Unique_Id__c, githubRequest.Action__c);
        }

        // NOTE: if the same record shows up in the same batch multiple times, only the last action should be honored

        // process all the adds
        if (requestsByAction.get('add') != null) {
            List<Github_Request__c> requestsToAdd = requestsByAction.get('add');
            for (Integer i = 0; i < requestsToAdd.size(); i++) {
                if (lastAction.get(requestsToAdd[i].Github_Unique_Id__c) != 'add') {
                    requestsToAdd.remove(i);
                }
            }
            GithubToAgileAccelerator.addWorkRecords(requestsToAdd);
        }
        
        // process all the attaches

        // process all the detaches
        
        // TODO: post results back to github 
    }
    

}